# httpProxy: "http://127.0.0.1:7890"

nodeLinker: node-modules
enableColors: true
npmRegistryServer: "https://registry.npmmirror.com"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
